language: cpp
compiler:
    - clang
    - gcc
env:
    - LIBRARY_COMBO=gnu-gnu-gnu
    - LIBRARY_COMBO=gnu-gnu-gnu SORT_ALG=timsort
    - LIBRARY_COMBO=ng-gnu-gnu
    - LIBRARY_COMBO=ng-gnu-gnu SORT_ALG=timsort
    - LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixed-abi
    - LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixed-abi SORT_ALG=timsort
matrix:
    exclude:
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu SORT_ALG=timsort
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixed-abi
        - compiler: gcc
          env: LIBRARY_COMBO=ng-gnu-gnu BASE_ABI=--disable-mixed-abi SORT_ALG=timsort
sudo: false
install: ./travis-deps.sh
before_script: >
    export LIBRARY_PATH=$HOME/staging/lib:$LIBRARY_PATH;
    export LD_LIBRARY_PATH=$HOME/staging/lib:$LD_LIBRARY_PATH;
    export CPATH=$HOME/staging/include:$CPATH;
    . $HOME/staging/share/GNUstep/Makefiles/GNUstep.sh;
script: >
    if [ -n $SORT_ALG ];
    then
        SORT_ALG_PARAM=--with-sort-algorithm=$SORT_ALG
    fi;
    ./configure $SORT_ALG_PARAM $BASE_API;
    make;
    make check;
addons:
    apt:
        packages:
            - cmake
            - pkg-config
            - libgnutls28-dev
            - libgmp-dev
            - libffi-dev
            - libicu-dev
            - libxml2-dev
            - libxslt1-dev
            - libssl-dev
            - libavahi-client-dev
            - zlib1g-dev
